function   (preset_bit)
    if   (NOT DEFINED PRESET_ARCH)
        message ("[Crisp] Target Architecture Not Defined. Use \"preset_bit_custom\" Instead")
        message (SEND_ERROR)
        return  ()
    endif()

    if    (DEFINED PRESET_ARCH_X86_64)
        set                    (PRESET_ARCH_BIT 64 PARENT_SCOPE)
        add_compile_definitions(PRESET_ARCH_BIT=64)
    elseif(DEFINED PRESET_ARCH_X86)
        set                    (PRESET_ARCH_BIT 32 PARENT_SCOPE)
        add_compile_definitions(PRESET_ARCH_BIT=32)
    endif()
endfunction()