function   (preset_endian)
    if   (NOT DEFINED PRESET_ARCH)
        message ("[Crisp] Target Architecture Not Defined. Use \"preset_endian_custom\" Instead")
        message (SEND_ERROR)
        return  ()
    endif()

    if    (DEFINED PRESET_ARCH_X86_64)
        set                    (PRESET_ARCH_ENDIAN_LITTLE ON PARENT_SCOPE)
        set                    (PRESET_ARCH_ENDIAN        ON PARENT_SCOPE)
        add_compile_definitions(PRESET_ARCH_ENDIAN_LITTLE)
    elseif(DEFINED PRESET_ARCH_X86)
        set                    (PRESET_ARCH_ENDIAN_LITTLE ON PARENT_SCOPE)
        set                    (PRESET_ARCH_ENDIAN        ON PARENT_SCOPE)
        add_compile_definitions(PRESET_ARCH_ENDIAN_LITTLE)
    endif()
endfunction()