function  (repo URL PATH)
    if    (UNIX AND NOT APPLE)
        if    (NOT EXISTS "/usr/bin/git")
            message("No Git Installation Found")
            message(SEND_ERROR)
        endif ()
    elseif(WIN32)
        if    (NOT EXISTS "C:/Program Files/Git/bin/git.exe")
            message("No Git Installation Found")
            message(SEND_ERROR "Abort")
        endif ()
    endif()
    execute_process(COMMAND git clone ${URL} WORKING_DIRECTORY ${PATH})
endfunction()